[package]
name = "in3-sys"
version = "0.11.0"
build = "build.rs"
links = "in3"

[dependencies]
libc = { version = "0.2.59", default-features = false }

[build-dependencies]
bindgen = "0.53.0"
regex = "1.3.1"
cc = "1.0"
