variables:
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - bindings
  - wasm
  - python
  - java
  - test
  - analysis
  - deploy
  - release

include:
  - template: Code-Quality.gitlab-ci.yml
  - local: "/c/ci.yml"
  - local: "/c/ci-analyse.yml"
  - local: "/c/ci-deploy.yml"
  - local: "/wasm/ci.yml"
  - local: "/java/ci.yml"
  - local: "/python/ci.yml"
##### local_docker_deploy_and_vulnerability_analysis #####

##### analyse #####

##### deploy #####
