
image: gcc
before_script:
 - apt-get update --yes
 - apt-get install --yes cmake

stages:
  - build

build-in3:
  stage: build
  tags:
    - short-jobs
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

xbuild-linux-64:
  image: docker:stable-dind
  stage: build
  tags:
    - short-jobs
  script:
    - docker run --rm dockcross/linux-x64 > ./dockcross
    - sh ./dockcross bash -c 'mkdir build; cd build; cmake ..; make  '
