stages:
  - build

build-in3:
  image: gcc
  stage: build
  tags:
    - short-jobs
  script:
    - apt-get update --yes
    - apt-get install --yes cmake
    - mkdir build
    - cd build
    - cmake ..
    - make

.xbuild:
  services:
    - docker:dind
  image: jonaskello/docker-and-compose:latest
  stage: build
  tags:
    - short-jobs
  script:
    - apk add --no-cache bash
    - docker run --rm "dockcross/$IMAGE" > ./dockcross
    - chmod +x ./dockcross
    - ./dockcross bash -c 'mkdir build; cd build; cmake ..; make  '
  variables:
     IMAGE: "linux-x64"

xbuild-linux-64:
  services:
    - docker:dind
  image: jonaskello/docker-and-compose:latest
  stage: build
  tags:
    - short-jobs
  script:
    - apk add --no-cache bash
    - docker run --rm dockcross/linux-x64 > ./dockcross
    - chmod +x ./dockcross
    - ./dockcross bash -c 'mkdir build; cd build; cmake ..; make  '

xbuild-windows-x64:
  extends: .xbuild
  variables:
     IMAGE: "windows-x64"

xbuild-windows-x32:
  extends: .xbuild
  variables:
     IMAGE: "windows-x32"
