variables:
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'
stages:
  - build
  - bindings
  - wasm
  - rust
  - python
  - dotnet
  - java
  - test
  - analysis
  - deploy
  - release

include:
  - local: "code-quality.gitlab-ci.yml"
  - local: "/c/ci.yml"
  - local: "/c/ci-analyse.yml"
  - local: "/c/ci-deploy.yml"
  - local: "/wasm/ci.yml"
  - local: "/java/ci.yml"
  - local: "/python/ci.yml"
  - local: "/dotnet/ci.yml"
  - local: "/rust/ci.yml"
##### local_docker_deploy_and_vulnerability_analysis #####

##### analyse #####

##### deploy #####
