stages:
  - build
  - deploy

build-in3:
  image: conanio/gcc8
  stage: build
  tags:
    - short-jobs
  script:
    - mkdir build
    - cd build
    - conan install .. --build libcurl
    - cmake ..
    - make
  artifacts:
    paths:
      - build/src

.xbuild:
  services:
    - docker:dind
  image: jonaskello/docker-and-compose:latest
  stage: build
  tags:
    - short-jobs
  artifacts:
    paths:
      - build/src
      - build/docs

  script:
    - apk add --no-cache bash
    - docker run --rm "dockcross/$IMAGE" > ./dockcross
    - chmod +x ./dockcross
    - ./dockcross bash -c "$INSTALL; sudo apt-get update ; sudo apt-get -y install doxygen ; mkdir build; cd build; conan install .. $CONAN_OPTS && cmake .. && make && ls -ltr src/*/"
  variables:
     IMAGE: "linux-x64"
     INSTALL: "cd ."
     CONAN_OPTS: ""



.conanbuild:
  stage: build
  tags:
    - short-jobs
  script:
    - mkdir build
    - cd build
    - conan install .. --build missing
    - cmake ..
    - make
    - ls -ltr src/*/lib/ src/*/bin/ 

gcc8-armv7:
  image: conanio/gcc8-armv7
  extends: .conanbuild
  artifacts:
    paths:
      - build/src

gcc8-armv7hf:
  image: conanio/gcc8-armv7hf
  extends: .conanbuild
  artifacts:
    paths:
      - build/src

gcc5:
  image: conanio/gcc5
  extends: .conanbuild
  artifacts:
    paths:
      - build/src

clang50:
  image: conanio/clang50
  extends: .conanbuild
  artifacts:
    paths:
      - build/src

  
linux-x64:
  extends: .xbuild
  variables:
     IMAGE: linux-x64


zephyr:
  image: agustinhenze/zephyr-arm
  stage: build
  tags:
    - short-jobs
  artifacts:
     paths:
      - src/zephyr/build
  script:
    - git clone https://github.com/zephyrproject-rtos/zephyr.git 
    - source zephyr/zephyr-env.sh
    - export ZEPHYR_SDK_INSTALL_DIR=$(find /opt/sdk -name "zephyr-sdk-*" | sort -rz | head -n 1)
    - cd src/zephyr; mkdir build; cd build
    - cmake -GNinja -DZEPHYR=true -DBOARD=nrf52840_pca10056 ..
    - ninja

  variables:
    LANG : C.UTF-8
    LC_ALL : C.UTF-8
    ZEPHYR_GCC_VARIANT : gccarmemb
    GCCARMEMB_TOOLCHAIN_PATH : /usr
    CROSS_COMPILE : /usr/bin/arm-none-eabi-


pages:
  tags:
    - short-jobs
  stage: deploy
  when: always
  environment:
    name: test-results
    url: https://in3.git-pages.slock.it/c/in3-core
  dependencies:
    - linux-x64
  script:
    - mkdir -p public/
    - cp -r build/docs/doc_doxygen/html/* public/
  artifacts:
    paths:
      - public



#windows-x64:
#  extends: .xbuild
#  variables:
#     IMAGE: windows-x64

#linux-armv5:
#  extends: .xbuild
#  variables:
#     IMAGE: linux-armv5

#linux-arm64:
#  extends: .xbuild
#  variables:
#     IMAGE: linux-arm64

#linux-armv6:
#  extends: .xbuild
#  variables:
#     IMAGE: linux-armv6

#linux-armv7:
#  extends: .xbuild
#  variables:
#     IMAGE: linux-armv7


#windows-x86:
#  extends: .xbuild
#  variables:
#     IMAGE: windows-x86

#manylinux-x64:
#  extends: .xbuild
#  variables:
#     IMAGE: manylinux-x64
#     CONAN_OPTS : --build libcurl
#     INSTALL: "apk add py-pip; pip install conan"
