[package]
name = "in3"
version = "0.1.0"
authors = ["slock.it <in3@slock.it>"]
description = "High level bindings to IN3 library"
edition = "2018"

[dependencies]
in3-sys = { path = "../in3-sys" }
libc = { version = "0.2", default-features = false }
reqwest = { version = "0.10", features = ["blocking","json"] }
tokio = { version = "0.2", features = ["macros"] }
serde_json = "1.0"
async-std = "1.5.0"
surf = "1.0.3"
serde = "1.0.106"
