name: C/C++ CI

on: [push]

jobs:
  test_macos:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: mkdir build; cd build; cmake -DTEST=true -DJAVA=false -DCMAKE_BUILD_TYPE=Debug ..
    - name: make
      run: cd build; make
    - name: test
      run: cd build; make test

  test_ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: mkdir build; cd build; cmake -DTEST=true -DJAVA=false -DTRANSPORTS=false -DBUILD_DOC=false -DIN3API=true -DIN3_LIB=false -DCMD=false -DCMAKE_BUILD_TYPE=Debug ..
    - name: make
      run: cd build; make
    - name: test
      run: cd build; make test

  test_win:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: cmake
      run: mkdir build; cd build; cmake -DTEST=true -DJAVA=false -DTRANSPORTS=false -DBUILD_DOC=false -DIN3API=true -DIN3_LIB=false -DCMD=false -DCMAKE_BUILD_TYPE=Debug ..
    - name: make
      run: cd build; make
    - name: test
      run: cd build; make test
